# Generated by Django 3.1.3 on 2020-12-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_category', models.CharField(max_length=150)),
                ('work_year', models.CharField(max_length=10)),
                ('place_name', models.CharField(max_length=250)),
                ('details', models.TextField()),
            ],
        ),
    ]
