# Generated by Django 3.0.5 on 2021-01-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Project_Category',
        ),
    ]
