# Generated by Django 3.2 on 2022-09-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pic'),
        ),
    ]
