# Generated by Django 3.0.5 on 2021-01-20 15:14

import ckeditor_uploader.fields
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0002_auto_20210119_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_header',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='protfolio',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
