# Generated by Django 3.2 on 2022-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0002_about_me_cover_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='about_cv'),
        ),
    ]
