# Generated by Django 3.0.5 on 2021-01-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0004_auto_20210120_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_header',
            name='my_picture',
            field=models.ImageField(default='atik.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
