# Generated by Django 3.0.5 on 2021-01-23 11:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0005_footer_header_my_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='about_img'),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_img'),
        ),
        migrations.AlterField(
            model_name='about_me',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_img'),
        ),
        migrations.AlterField(
            model_name='protfolio',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio_img'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='service_img'),
        ),
    ]
