# Generated by Django 3.0.5 on 2021-01-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio_app', '0006_auto_20210123_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='contact_sidebar_image',
            field=models.ImageField(default='image.jpg', upload_to='contact_sidebar'),
            preserve_default=False,
        ),
    ]
